### ISSUE TITLE
Multiple include during testing

### ISSUE THREAD

**Issue by morenDev** [Artem-Schander/L5Modular#19]
PHP Fatal error:  Cannot redeclare is_active_menu() (previously declared in /xxx/app/Modules/Admin/helper.php:29) in /xxx/app/Modules/Admin/helper.php on line 29

include_once could solve the issue. Why do you use include here?

**Comment by Artem-Schander** [comment]
Hi,
your problem is not a multiple include (in fact every file is getting included once anyway).
Since the function in your `helper` files are in the same scope, you should either give them a unique name or check if there is already a function with the same name.

Laravel is doing the same thing in its helpers file. F.A.
```
if (! function_exists('array_add')) {
    /**
     * Add an element to an array using "dot" notation if it doesn't exist.
     *
     * @param  array   $array
     * @param  string  $key
     * @param  mixed   $value
     * @return array
     */
    function array_add($array, $key, $value)
    {
        return Arr::add($array, $key, $value);
    }
}
```

**Comment by morenDev** [comment]
@Artem-Schander Thanks!!
I had a mess in    function_exists('xxx')
