### ISSUE TITLE
How to use the helper.php?

### ISSUE THREAD

**Issue by jericopulvera** [Artem-Schander/L5Modular#32]
How to use the helper.php in a view?

**Comment by Artem-Schander** [comment]
since the helper file ist getting loaded by the `ModuleServiceProvider.php`, you can use it all over your app.
So if you have a function named `generateRandomNumber` in any of your Modules `helper.php` file, you can call it like this: `<?php echo generateRandomNumber() ?>`.
In a blade view it would look like `{{ generateRandomNumber() }}`
